# Spring Config
spring:
  datasource:
    url: jdbc:h2:file:./assets/database
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

# Logging Config
logging:
  file:
    path: logs/
    name: logs/victBot.log

# Custom Config
vict:
  twitter:
    fix: false
  discord:
    token: ${BOT_TOKEN}
    guilds: ${BOT_GUILDS}
# Procedure Scheduling
  procedure:
    logging:
      cron: "0 0 * * * ?"
    reminder:
      cron: "0 * * * * ?"