discord:
  token: ${BOT_TOKEN}
  guild: ${BOT_GUILD}
procedure:
  increment: 1000
  rate: 60000
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
application:
  name: VictBot
twitter:
  fix: true
springdoc:
  swagger-ui:
    path: /