spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./assets/database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never

application:
  name: VictBot

springdoc:
  swagger-ui:
    path: /

vict:
  twitter:
    fix: false
  discord:
    token: ${BOT_TOKEN}
    guilds: ${BOT_GUILDS}
  procedure:
    logging:
      cron: "0 0 * * * ?"
    reminder:
      cron: "0 * * * * ?"
  stable-diffusion:
    url: ${STABLE_DIFFUSION_URL}