# Spring Config
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  application:
    name: VictBot


# Swagger Config
springdoc:
  swagger-ui:
    path: /


# Custom Config
vict:
  # AI Dependencies
  stable-diffusion:
    url: ${STABLE_DIFFUSION_URL}